-- ============================================================
-- 더브릿지 ERP Supabase Schema
-- Supabase SQL Editor에서 실행하세요
-- ============================================================

-- 1. 주문 테이블
create table if not exists orders (
  id text primary key,
  date text,
  time text,
  customer text,
  phone text,
  items jsonb default '[]',
  payment text default '미입금',
  address text,
  note text,
  status text default '접수',
  manager text default '',
  created_at timestamptz default now()
);

-- 2. 재고 테이블
create table if not exists inventory (
  id bigint generated by default as identity primary key,
  fabric text not null,
  color text default '',
  stock numeric default 0
);

-- 3. 고객 테이블
create table if not exists customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text default '',
  address text default '',
  total_orders int default 0,
  last_order text,
  note text default ''
);

-- 4. 입출고 로그 테이블
create table if not exists logs (
  id text primary key,
  date text,
  time text,
  type text,
  item_no text default '',
  fabric text,
  color text default '',
  qty numeric default 0,
  cost_price numeric default 0,
  ref text default '',
  note text default '',
  created_at timestamptz default now()
);

-- 5. 담당자 테이블
create table if not exists managers (
  id bigint generated by default as identity primary key,
  name text unique not null
);

-- ============================================================
-- RLS (Row Level Security) - anon 키로 접근 허용
-- ============================================================
alter table orders enable row level security;
alter table inventory enable row level security;
alter table customers enable row level security;
alter table logs enable row level security;
alter table managers enable row level security;

-- 모든 테이블에 anon 읽기/쓰기 허용 정책
create policy "Allow all for anon" on orders for all using (true) with check (true);
create policy "Allow all for anon" on inventory for all using (true) with check (true);
create policy "Allow all for anon" on customers for all using (true) with check (true);
create policy "Allow all for anon" on logs for all using (true) with check (true);
create policy "Allow all for anon" on managers for all using (true) with check (true);

-- ============================================================
-- 기본 재고 데이터 삽입
-- ============================================================
insert into inventory (fabric, color, stock) values
  ('린넨코튼', '', 421),
  ('린넨코튼15수', '', 251),
  ('강화소창', '', 93),
  ('린넨100', '', 122),
  ('라미36수', '', 107),
  ('쉬폰', '', 370),
  ('무명13수', '', 189),
  ('마8수', '', 181),
  ('트위드', '', 229),
  ('라미60수', '', 56),
  ('린넨', '', 103),
  ('린넨코튼 튤립', '', 72),
  ('뜨왈', '', 70),
  ('13수 무명', '', 106),
  ('린넨코튼 15수', '', 102)
on conflict do nothing;

-- 기본 담당자 삽입
insert into managers (name) values
  ('실장님'), ('고문님'), ('장부장님'), ('송미송'), ('김민주'), ('손희우')
on conflict (name) do nothing;
